### ISSUE TITLE
调节编辑器宽度后，文档图标应和内容对齐

### ISSUE THREAD

**Issue by StarDustSheep** [frostime/siyuan-center-width#1]
![image](https://github.com/svtardust/Calendar-heatmap/assets/114859111/2c84ff05-95b1-4461-b84a-fa2b3d795c89)
![image](https://github.com/frostime/siyuan-center-width/assets/114859111/1f079114-3b6c-41ba-83d5-0b2da795fe00)

想办法让div.protyle-background__iconw和它们对齐吧

**Comment by frostime** [comment]
ok
