### ISSUE TITLE
调整位置，允许左右padding不一样

### ISSUE THREAD

**Issue by frostime** [frostime/siyuan-center-width#12]

**Comment by TCOTC** [comment]
现在有点需要这个。如果能让左侧靠边，右侧留出大于 250px (这个还跟 #8 有关) 的空位就可以配合「侧边备注」插件使用了：

![image](https://github.com/frostime/siyuan-center-width/assets/78434827/e367c96d-cc3f-4508-a3a3-b0dacc3a3141)
