### ISSUE TITLE
功能建议| 支持闪卡界面保持等宽

### ISSUE THREAD

**Issue by JOYCELEEEEE** [frostime/siyuan-center-width#13]
闪卡界面全屏后，貌似不能保持和编辑器同样的宽度

**Comment by frostime** [comment]
好的，我个人用闪卡比较少，所以之前没考虑过这方面，后面会看看的。

**Comment by JOYCELEEEEE** [comment]
> 好的，我个人用闪卡比较少，所以之前没考虑过这方面，后面会看看的。

2.10.12 版本自动适配，大佬不用烦心了~
