### ISSUE TITLE
请问能否增加功能，使用Ctrl+鼠标滚轮调整宽度？

### ISSUE THREAD

**Issue by pisceswb** [frostime/siyuan-center-width#16]
如题，能否像浏览器一样，使用Ctrl+鼠标滚轮调整宽度？谢谢！

**Comment by frostime** [comment]
容易和思源自带的调整字号功能冲突，这个就不考虑了。谢谢！

![image](https://github.com/frostime/siyuan-center-width/assets/27268127/7d864c2d-0c7f-4312-87f0-ad3a5bf1ed4c)
