### ISSUE TITLE
2.11.4版本下，不适配了。

### ISSUE THREAD

**Issue by MarshRainy** [frostime/siyuan-center-width#18]
复杂模式，题头不变，正文变来变去。简单模式，都不变了。

**Comment by frostime** [comment]
我这边还一切正常。

![image](https://github.com/frostime/siyuan-center-width/assets/27268127/0d1f0512-41d5-4c0f-9000-d1b334925763)


 要不你先检查一下是否是你本地的问题，或者社区群里面问一下还有没有别的人也出现这种问题？

**Comment by frostime** [comment]
您好，请问还有这个问题吗？

我先关闭这个 issue 了，如果还是有问题可以继续在这个下面发言。

**Comment by James-Y-Fan** [comment]
2.12.0 dev 版不生效了，麻烦看下

**Comment by frostime** [comment]
又有人报告了类似的问题，可能确实存在问题，但是我现在无法复现。

如果有类似的问题，移步到 #19
