### ISSUE TITLE
v2.12.0 版本下，出现了插件无法生效的情况

### ISSUE THREAD

**Issue by James-Y-Fan** [frostime/siyuan-center-width#19]
如题
![image](https://github.com/frostime/siyuan-center-width/assets/51410244/2a20125a-bfc5-4ab3-b9e6-5ce626e0adac)

大佬，有空看看

**Comment by frostime** [comment]
![image](https://github.com/frostime/siyuan-center-width/assets/27268127/0bc7b3b8-22ce-4e1d-8fcd-e97bda1ab0c3)

你好，我刚刚安装了最新的 dev 版本，似乎没有出现问题。

目前已经有不止你一人提出类似的情况 #18 ，可能确实存在我尚未知晓的问题。但是在本地无法复现你说的情况下，我也无法定位到问题所在。

你可以先试试清空网络缓存、重装插件等方案看能否回复正常。

可以的话，最好请你回忆研究一下是什么触发了这个问题，看看能否提供稳定触发的方法。
比如可以新建一个工作空间，尝试复现你之前的操作看看能不能触发让插件失效的情况。

**Comment by James-Y-Fan** [comment]
重新安装之后，变成这样
![image](https://github.com/frostime/siyuan-center-width/assets/51410244/b1173020-3fe6-43ae-8a01-8578ec69525a)
关掉笔记，再重新打开，又变成这样了
![image](https://github.com/frostime/siyuan-center-width/assets/51410244/2a0165ee-c5cf-4055-9af6-b7170ca29904)

**Comment by frostime** [comment]
你可以新建一个干净的工作空间，然后下载插件看看插件是否正常生效？

如果能正常生效，那可能是某个操作触发了隐藏的 bug。

现在我本地使用的是正常的，也不知道你这种情况是怎么触发的。我尽量留意看看能不能触发。

实在不行在我修复前你就先用全宽模式凑合一下吧。

**Comment by James-Y-Fan** [comment]
新建的工作空间正常。
过几天，发新版，我再看看是不是正常。

**Comment by frostime** [comment]
> 新建的工作空间正常。 过几天，发新版，我再看看是不是正常。

嗯，那就应该是某个操作触发了这个 bug，你后面可以留意下看看是啥操作触发的

**Comment by TCOTC** [comment]
不确定是什么原因导致的，我在 v3.0.4 出现了无法生效的情况。

最后通过迁移工作空间（导出 Data → 导入 Data）解决了。
