### ISSUE TITLE
固定值的编辑器宽度

### ISSUE THREAD

**Issue by QQQOrange** [frostime/siyuan-center-width#20]
如果分窗口的情况下原来的比例就需要重新更改比例以适配阅读，要是可以同时设置百分比和宽度就可以避免这种情况

**Comment by frostime** [comment]
你是说独立小窗口内的宽度吗？那个我目前的处理是固定 94% 比例，不随设置变化。主要的考虑是在小窗口下一般会希望尽可能扩大阅读区域，而调整宽度的意义不太大，所以就没有设定为可调整的宽度。

**Comment by QQQOrange** [comment]
> 你是说独立小窗口内的宽度吗？那个我目前的处理是固定 94% 比例，不随设置变化。主要的考虑是在小窗口下一般会希望尽可能扩大阅读区域，而调整宽度的意义不太大，所以就没有设定为可调整的宽度。

是的 固定值的编辑器宽度，主要是当排列两个窗口的时候，固定比例显示就很奇怪，如果有一个固定宽度数值，那么在主编辑器被副编辑器窗口挤压的时候 阅读宽度就不会改变

**Comment by frostime** [comment]
> > 你是说独立小窗口内的宽度吗？那个我目前的处理是固定 94% 比例，不随设置变化。主要的考虑是在小窗口下一般会希望尽可能扩大阅读区域，而调整宽度的意义不太大，所以就没有设定为可调整的宽度。
> 
> 是的 固定值的编辑器宽度，主要是当排列两个窗口的时候，固定比例显示就很奇怪，如果有一个固定宽度数值，那么在主编辑器被副编辑器窗口挤压的时候 阅读宽度就不会改变

主要是实现起来方便吧，你的提案应该和这个相关 #8 。
后面有空我调整一下，这段时间基本没空写插件，而且小窗下 94% 的变动也不大，先凑合用着。我有空了再优化。

**Comment by QQQOrange** [comment]
> > > 你是说独立小窗口内的宽度吗？那个我目前的处理是固定 94% 比例，不随设置变化。主要的考虑是在小窗口下一般会希望尽可能扩大阅读区域，而调整宽度的意义不太大，所以就没有设定为可调整的宽度。
> > 
> > 
> > 是的 固定值的编辑器宽度，主要是当排列两个窗口的时候，固定比例显示就很奇怪，如果有一个固定宽度数值，那么在主编辑器被副编辑器窗口挤压的时候 阅读宽度就不会改变
> 
> 主要是实现起来方便吧，你的提案应该和这个相关 #8 。 后面有空我调整一下，这段时间基本没空写插件，而且小窗下 94% 的变动也不大，先凑合用着。我有空了再优化。

好呀好呀 有盼头比啥都强 笔芯
