### ISSUE TITLE
文档上面的图标和按钮需要跟文档标题对齐

### ISSUE THREAD

**Issue by TCOTC** [frostime/siyuan-center-width#22]
文档上面的图标和按钮能不能也改一下宽度，跟文档标题对齐：

![image](https://github.com/frostime/siyuan-center-width/assets/78434827/196713f1-56b3-42b7-8141-ed61af583966)

**Comment by frostime** [comment]
这个我应该都已经改了才对

**Comment by frostime** [comment]
我明天更新了 v12 以后再看看吧。
