### ISSUE TITLE
无法展开已折叠的列表

### ISSUE THREAD

**Issue by TCOTC** [frostime/siyuan-center-width#23]
使用 Savor 主题，插件设置编辑器宽度大于等于 90% ，思源界面字号较小时，无法展开已折叠的列表

![image](https://github.com/frostime/siyuan-center-width/assets/78434827/cc7aea16-9f3c-4d95-916f-669f660ee444)

**Comment by frostime** [comment]
是主编辑器还是反链面板？

宽度插件应该没有对反链面板生效。

另外我这里用 savor 主题也没有遇到你说的问题。

![image](https://github.com/frostime/siyuan-center-width/assets/27268127/c1d1e3af-6e31-4e6f-8876-14cde1d3b925)

**Comment by TCOTC** [comment]
本 issue 的问题是编辑器而不是反链面板。

这个问题不确定是否会跟 Windows 系统的屏幕缩放比例有关，总之现在也没人能帮我复现（摊手

**Comment by frostime** [comment]
是一直都有这个问题还是这次更新后有的？

我这次没有更新什么内容，就是把主编辑器的最小边距从 10px 改成了 15px 防止把块 gutter 按钮挡住。

**Comment by TCOTC** [comment]
可能以前也有同样的问题，只是这次更新之后我把编辑器宽度设置为大于 90% 了才发现

**Comment by frostime** [comment]
缺少足够的信息，先放着吧。

反正一般也不会调整到 90% 以上。

**Comment by TCOTC** [comment]
研究了一下，应该是 Savor 主题的问题（其他主题都没问题），issue 先关闭了
