### ISSUE TITLE
能否实现只设置某一篇文章中编辑器的大小呢？

### ISSUE THREAD

**Issue by z2023711** [frostime/siyuan-center-width#25]
如图，我只想要这篇文章的编辑器宽度为100%，其他的为另一个标准，请问有办法实现吗？
![image](https://github.com/user-attachments/assets/16e63bfc-726a-4e2c-99d2-395047f57dbf)

**Comment by frostime** [comment]
对于特定文章想要设置全宽的话，建议直接在编辑器中启用‘自适应宽度’。

![image](https://github.com/user-attachments/assets/1d9a8786-1612-4d17-a100-b1e3d7b2f785)

**Comment by z2023711** [comment]
感谢，这个方法确实有效
