### ISSUE TITLE
增加百分比以外的模式

### ISSUE THREAD

**Issue by frostime** [frostime/siyuan-center-width#8]

**Comment by yylic** [comment]
这个模式可以固定宽度吗（如默认max-width: 800px），这样可以让界面不会动态变化，百分比那个会根据主界面宽度动态变化，搜了好久都没找到好的办法弄默认固定最大宽度。
这个帖子下面评论有个老哥弄了个固定宽度，但我试用了感觉不是很稳定，有点bug，楼主可以借鉴参考下：https://ld246.com/article/1629016150392

**Comment by frostime** [comment]
我试一下，应该可以

**Comment by zhoutaosheng** [comment]
> 我试一下，应该可以

表示同样需要固定宽度，固定宽度的好处是：在不同分辨率的显示器上，有一致的表现，会非常舒服
