### ISSUE TITLE
when set to 100% ref count icon on the right disappears

### ISSUE THREAD

**Issue by omega3** [frostime/siyuan-center-width#9]
When set to 100% ref count icon on the right disappears.
Compare the difference:
98% - it is visible
https://i.imgur.com/d1oJma4.png
100% - disappears
https://i.imgur.com/vabEoJC.png

If possible, please make it stick and visible with 100%.

**Comment by frostime** [comment]
Fixed in v0.1.2, the latest version will be published soon, thanks for feedback!

![image](https://github.com/frostime/siyuan-center-width/assets/27268127/240f4031-a7da-44ff-a351-da53408380cd)
